<?php
/**
 * Created by PhpStorm.
 * User: lqj
 * Date: 2017/11/5
 * Time: 10:20
 */

namespace treeNav;


use yii\bootstrap\Dropdown;
use yii\bootstrap\Nav;
use yii\helpers\ArrayHelper;

class NavTreeX extends Nav
{
    public $items=[];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        TreeAssetX::register($this->getView());
        return parent::run(); // TODO: Change the autogenerated stub
    }

    protected function renderDropdown($items, $parentItem)
    {
        return Dropdown::widget([
            'options'=>ArrayHelper::getValue($parentItem,'dropDownOptions',['class'=>'dropdown-menu']),
            'items'=>$items,
            'encodeLabels'=>false,
            'view'=>$this->getView(),
        ]);
    }

}